"""
Response Processor

Post-processes raw text generated by local SLM, extracts source citations from retrieved chunks,
formats clean markdown, and strips prompt artifacts.
"""

import re
from typing import List, Dict, Any
from OfflineTutorAI.models.chunk_model import CurriculumChunk


class ResponseProcessor:
    """Cleans and annotates tutor outputs."""

    def process_response(
        self,
        raw_text: str,
        retrieved_chunks: List[CurriculumChunk]
    ) -> Dict[str, Any]:
        """
        Processes raw model text and extracts metadata citations.
        
        Returns:
            Dict containing 'cleaned_answer' and 'sources' list.
        """
        cleaned_text = self._clean_markdown(raw_text)
        sources = self._extract_sources(retrieved_chunks)

        return {
            "cleaned_answer": cleaned_text,
            "sources": sources
        }

    def _clean_markdown(self, text: str) -> str:
        """Strips system token leakages and cleans extra trailing whitespace."""
        text = re.sub(r"<\|system\|>.*?<\|end\|>", "", text, flags=re.DOTALL)
        text = re.sub(r"<\|assistant\|>", "", text)
        text = re.sub(r"<\|end\|>", "", text)
        return text.strip()

    def _extract_sources(self, chunks: List[CurriculumChunk]) -> List[Dict[str, Any]]:
        """Extracts unique source citations from retrieved curriculum chunks."""
        sources = []
        seen_keys = set()

        for chunk in chunks:
            key = (chunk.subject, chunk.chapter, chunk.topic, chunk.source_page)
            if key not in seen_keys:
                seen_keys.add(key)
                sources.append({
                    "board": chunk.board,
                    "class": chunk.class_name,
                    "subject": chunk.subject,
                    "chapter": chunk.chapter,
                    "topic": chunk.topic,
                    "source_page": chunk.source_page,
                    "chunk_id": chunk.chunk_id
                })
        return sources
